"""add handbook table

Revision ID: b64f562f0aed
Revises: 69a62a83a8f7
Create Date: 2026-09-19 04:07:39.935058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64f562f0aed'
down_revision: Union[str, None] = '69a62a83a8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_announcement_reads_user_id', table_name='announcement_reads')
    op.drop_index('idx_announcements_expires_at', table_name='announcements')
    op.drop_index('idx_announcements_status', table_name='announcements')
    op.drop_index('idx_chat_messages_room_created', table_name='chat_messages')
    op.drop_index('idx_chat_room_members_user', table_name='chat_room_members')
    op.drop_index('idx_message_reads_message_id', table_name='message_reads')
    op.drop_index('idx_message_reads_user_id', table_name='message_reads')
    op.drop_index('idx_payroll_salary_month', table_name='payroll')
    op.drop_index('idx_payroll_user_month', table_name='payroll')
    op.drop_index('idx_previous_company_details_user_profile_id', table_name='previous_company_details')
    op.drop_index('idx_starred_messages_message_id', table_name='starred_messages')
    op.drop_index('idx_starred_messages_user_id', table_name='starred_messages')
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index('idx_starred_messages_user_id', 'starred_messages', ['user_id'], unique=False)
    op.create_index('idx_starred_messages_message_id', 'starred_messages', ['message_id'], unique=False)
    op.create_index('idx_previous_company_details_user_profile_id', 'previous_company_details', ['user_profile_id'], unique=False)
    op.create_index('idx_payroll_user_month', 'payroll', ['user_id', 'salary_month'], unique=True)
    op.create_index('idx_payroll_salary_month', 'payroll', ['salary_month'], unique=False)
    op.create_index('idx_message_reads_user_id', 'message_reads', ['user_id'], unique=False)
    op.create_index('idx_message_reads_message_id', 'message_reads', ['message_id'], unique=False)
    op.create_index('idx_chat_room_members_user', 'chat_room_members', ['user_id'], unique=False)
    op.create_index('idx_chat_messages_room_created', 'chat_messages', ['room_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_announcements_status', 'announcements', ['status'], unique=False)
    op.create_index('idx_announcements_expires_at', 'announcements', ['expires_at'], unique=False)
    op.create_index('idx_announcement_reads_user_id', 'announcement_reads', ['user_id'], unique=False)
    op.drop_table('handbooks')
    # ### end Alembic commands ###
