"""updated leave table

Revision ID: ca30749f40b3
Revises: ba2a7615276a
Create Date: 2026-06-24 04:46:27.406223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca30749f40b3'
down_revision: Union[str, None] = 'ba2a7615276a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('duration_days', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaves', 'duration_days')
    # ### end Alembic commands ###
